import { z } from 'zod';

export const SubtitleCueSchema = z.object({
  start: z.number().min(0),
  end: z.number().min(0),
  text: z.string().min(1),
});

export type SubtitleCue = z.infer<typeof SubtitleCueSchema>;

export const SubtitleTrackSchema = z.object({
  videoId: z.string(),
  language: z.string(),
  isAutoGenerated: z.boolean(),
  cues: z.array(SubtitleCueSchema),
});

export type SubtitleTrack = z.infer<typeof SubtitleTrackSchema>;

export const SubtitleQuerySchema = z.object({
  language: z.string().optional(),
});

export type SubtitleQuery = z.infer<typeof SubtitleQuerySchema>;

export const SubtitleResponseSchema = z.object({
  data: SubtitleTrackSchema.nullable(),
});

export type SubtitleResponse = z.infer<typeof SubtitleResponseSchema>;
