export interface SubtitleCue {
  start: number;  // seconds
  end: number;    // seconds
  text: string;
}

export interface SubtitleTrack {
  videoId: string;
  language: string;
  isAutoGenerated: boolean;
  cues: SubtitleCue[];
}

export interface SubtitleParser {
  parse(vttContent: string, videoId: string, language: string): SubtitleTrack;
}
