import { SubtitleParser, SubtitleCue, SubtitleTrack } from './subtitle-parser.interface';

export class VttParser implements SubtitleParser {
  parse(vttContent: string, videoId: string, language: string): SubtitleTrack {
    const lines = vttContent.split(/\r?\n/);
    const cues: SubtitleCue[] = [];
    let i = 0;

    // Skip WEBVTT header and any metadata
    while (i < lines.length && !lines[i].includes('-->')) {
      i++;
    }

    while (i < lines.length) {
      const line = lines[i].trim();
      if (line.includes('-->')) {
        // Parse timestamp line
        const [startStr, endStr] = line.split('-->').map(s => s.trim());
        const start = this.parseTimestamp(startStr);
        const end = this.parseTimestamp(endStr);
        // Collect text lines until empty line or end
        const textLines: string[] = [];
        i++;
        while (i < lines.length && lines[i].trim() !== '') {
          textLines.push(lines[i].trim());
          i++;
        }
        const text = this.stripHtml(textLines.join(' '));
        if (text) {
          cues.push({ start, end, text });
        }
      } else {
        i++;
      }
    }

    // Sort by start time
    cues.sort((a, b) => a.start - b.start);

    return {
      videoId,
      language,
      isAutoGenerated: false, // default, can be overridden
      cues,
    };
  }

  private parseTimestamp(timestamp: string): number {
    // Format: HH:MM:SS.mmm or MM:SS.mmm
    const parts = timestamp.split(':');
    let hours = 0;
    let minutes = 0;
    let seconds = 0;
    if (parts.length === 3) {
      hours = parseInt(parts[0], 10);
      minutes = parseInt(parts[1], 10);
      seconds = parseFloat(parts[2]);
    } else if (parts.length === 2) {
      minutes = parseInt(parts[0], 10);
      seconds = parseFloat(parts[1]);
    }
    return hours * 3600 + minutes * 60 + seconds;
  }

  private stripHtml(text: string): string {
    // Remove HTML tags and VTT formatting like <c>, </c>
    return text
      .replace(/<[^>]+>/g, '')
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .trim();
  }
}