import { pgTable, text, integer, boolean, timestamp, index } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { videos } from '../video/video.schema';

export const subtitleSegments = pgTable('subtitle_segments', {
  id: text('id').primaryKey().default(sql`gen_random_uuid()`),
  videoId: text('video_id')
    .notNull()
    .references(() => videos.id, { onDelete: 'cascade' }),
  startMs: integer('start_ms').notNull(),
  endMs: integer('end_ms').notNull(),
  text: text('text').notNull(),
  segmentIndex: integer('segment_index').notNull(),
  language: text('language').notNull().default('en'),
  isAutoGenerated: boolean('is_auto_generated').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('idx_subtitle_video_id').on(table.videoId),
  index('idx_subtitle_start_ms').on(table.startMs),
]);
