import { Injectable, Inject } from '@nestjs/common';
import { SubtitleRepository } from './subtitle.repository';
import { VideoService } from '../video/video.service';
import { SubtitleParser, SubtitleTrack } from './parsers/subtitle-parser.interface';
import { YtdlpExecutor } from './executors/ytdlp.executor.interface';
import { AppError, ErrorCategory } from '../../common/errors/app-error';
import * as fs from 'fs/promises';
import * as os from 'os';
import * as path from 'path';

@Injectable()
export class SubtitleService {
  constructor(
    private readonly subtitleRepository: SubtitleRepository,
    private readonly videoService: VideoService,
    @Inject('SubtitleParser') private readonly subtitleParser: SubtitleParser,
    @Inject('YtdlpExecutor') private readonly ytdlpExecutor: YtdlpExecutor,
  ) {}

  async extractForVideo(videoId: string, language: string = 'en'): Promise<SubtitleTrack> {
    // Verify video exists
    await this.videoService.findById(videoId);
    
    // Check cache
    const cached = await this.subtitleRepository.findByVideoId(videoId, language);
    if (cached.length > 0) {
      // Convert cached segments to SubtitleTrack
      return {
        videoId,
        language,
        isAutoGenerated: cached[0]?.isAutoGenerated ?? false,
        cues: cached.map(seg => ({
          start: seg.startMs / 1000,
          end: seg.endMs / 1000,
          text: seg.text,
        })),
      };
    }

    // Extract subtitles via yt-dlp
    const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'subtitle-'));
    try {
      // Need youtubeId from video record
      const video = await this.videoService.findById(videoId);
      const vttContent = await this.ytdlpExecutor.getSubtitles(video.youtubeId, language, tempDir);
      
      // Parse VTT
      const track = this.subtitleParser.parse(vttContent, videoId, language);
      
      // Store segments
      const segments = track.cues.map((cue, index) => ({
        videoId,
        startMs: Math.round(cue.start * 1000),
        endMs: Math.round(cue.end * 1000),
        text: cue.text,
        segmentIndex: index,
        language,
        isAutoGenerated: track.isAutoGenerated,
      }));
      await this.subtitleRepository.createMany(segments);
      
      return track;
    } finally {
      // Clean up temp directory
      await fs.rm(tempDir, { recursive: true, force: true }).catch(() => {});
    }
  }

  async findByVideoId(videoId: string, language?: string): Promise<SubtitleTrack | null> {
    const segments = await this.subtitleRepository.findByVideoId(videoId, language);
    if (segments.length === 0) return null;
    return {
      videoId,
      language: segments[0].language,
      isAutoGenerated: segments[0].isAutoGenerated,
      cues: segments.map(seg => ({
        start: seg.startMs / 1000,
        end: seg.endMs / 1000,
        text: seg.text,
      })),
    };
  }
}