import { Injectable } from '@nestjs/common';
import { eq, and } from 'drizzle-orm';
import { subtitleSegments } from './subtitle.schema';
import { db } from '../../common/database';

export interface CreateSegmentData {
  videoId: string;
  startMs: number;
  endMs: number;
  text: string;
  segmentIndex: number;
  language: string;
  isAutoGenerated: boolean;
}

@Injectable()
export class SubtitleRepository {
  async findByVideoId(videoId: string, language?: string) {
    const conditions = [eq(subtitleSegments.videoId, videoId)];
    if (language) {
      conditions.push(eq(subtitleSegments.language, language));
    }
    return db
      .select()
      .from(subtitleSegments)
      .where(and(...conditions))
      .orderBy(subtitleSegments.segmentIndex);
  }

  async create(data: CreateSegmentData) {
    const result = await db
      .insert(subtitleSegments)
      .values({
        videoId: data.videoId,
        startMs: data.startMs,
        endMs: data.endMs,
        text: data.text,
        segmentIndex: data.segmentIndex,
        language: data.language,
        isAutoGenerated: data.isAutoGenerated,
      })
      .returning();
    return result[0];
  }

  async createMany(data: CreateSegmentData[]) {
    if (data.length === 0) return [];
    const result = await db
      .insert(subtitleSegments)
      .values(data)
      .returning();
    return result;
  }

  async existsForVideo(videoId: string): Promise<boolean> {
    const result = await db
      .select({ id: subtitleSegments.id })
      .from(subtitleSegments)
      .where(eq(subtitleSegments.videoId, videoId))
      .limit(1);
    return result.length > 0;
  }
}