import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { SubtitleService } from '../subtitle.service';
import { SubtitleRepository } from '../subtitle.repository';
import { VideoService } from '../../video/video.service';
import { SubtitleParser, SubtitleTrack } from '../parsers/subtitle-parser.interface';
import { YtdlpExecutor } from '../executors/ytdlp.executor.interface';
import { AppError, ErrorCategory } from '../../../common/errors/app-error';
import * as fs from 'fs/promises';

// Mock fs/promises
vi.mock('fs/promises', () => ({
  mkdtemp: vi.fn(),
  rm: vi.fn(),
}));

describe('SubtitleService', () => {
  let subtitleService: SubtitleService;
  let mockSubtitleRepository: {
    findByVideoId: ReturnType<typeof vi.fn>;
    createMany: ReturnType<typeof vi.fn>;
  };
  let mockVideoService: {
    findById: ReturnType<typeof vi.fn>;
  };
  let mockSubtitleParser: {
    parse: ReturnType<typeof vi.fn>;
  };
  let mockYtdlpExecutor: {
    getMetadata: ReturnType<typeof vi.fn>;
    getSubtitles: ReturnType<typeof vi.fn>;
  };

  beforeEach(() => {
    vi.clearAllMocks();
    
    mockSubtitleRepository = {
      findByVideoId: vi.fn(),
      createMany: vi.fn(),
    };
    mockVideoService = {
      findById: vi.fn(),
    };
    mockSubtitleParser = {
      parse: vi.fn(),
    };
    mockYtdlpExecutor = {
      getMetadata: vi.fn(),
      getSubtitles: vi.fn(),
    };

    subtitleService = new SubtitleService(
      mockSubtitleRepository as unknown as SubtitleRepository,
      mockVideoService as unknown as VideoService,
      mockSubtitleParser as unknown as SubtitleParser,
      mockYtdlpExecutor as unknown as YtdlpExecutor,
    );

    // Default mocks for fs
    vi.mocked(fs.mkdtemp).mockResolvedValue('/tmp/subtitle-test');
    vi.mocked(fs.rm).mockResolvedValue(undefined);
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  describe('extractForVideo', () => {
    it('should return cached subtitles when available', async () => {
      const cachedSegments = [
        {
          videoId: 'video-1',
          startMs: 1000,
          endMs: 3000,
          text: 'Hello',
          segmentIndex: 0,
          language: 'en',
          isAutoGenerated: false,
        },
        {
          videoId: 'video-1',
          startMs: 4000,
          endMs: 6000,
          text: 'World',
          segmentIndex: 1,
          language: 'en',
          isAutoGenerated: false,
        },
      ];

      mockVideoService.findById.mockResolvedValue({ id: 'video-1', youtubeId: 'yt-123' });
      mockSubtitleRepository.findByVideoId.mockResolvedValue(cachedSegments);

      const result = await subtitleService.extractForVideo('video-1', 'en');

      expect(result.videoId).toBe('video-1');
      expect(result.language).toBe('en');
      expect(result.isAutoGenerated).toBe(false);
      expect(result.cues).toHaveLength(2);
      expect(result.cues[0]).toEqual({ start: 1, end: 3, text: 'Hello' });
      expect(result.cues[1]).toEqual({ start: 4, end: 6, text: 'World' });
      expect(mockYtdlpExecutor.getSubtitles).not.toHaveBeenCalled();
      expect(mockSubtitleParser.parse).not.toHaveBeenCalled();
    });

    it('should extract, parse, and cache on cache miss', async () => {
      const vttContent = `WEBVTT

00:00:01.000 --> 00:00:03.000
Hello from YouTube

00:00:04.000 --> 00:00:06.000
Second line
`;
      const parsedTrack: SubtitleTrack = {
        videoId: 'video-1',
        language: 'en',
        isAutoGenerated: false,
        cues: [
          { start: 1, end: 3, text: 'Hello from YouTube' },
          { start: 4, end: 6, text: 'Second line' },
        ],
      };

      mockVideoService.findById.mockResolvedValue({ id: 'video-1', youtubeId: 'yt-123' });
      mockSubtitleRepository.findByVideoId.mockResolvedValue([]);
      mockYtdlpExecutor.getSubtitles.mockResolvedValue(vttContent);
      mockSubtitleParser.parse.mockReturnValue(parsedTrack);
      mockSubtitleRepository.createMany.mockResolvedValue([]);

      const result = await subtitleService.extractForVideo('video-1', 'en');

      expect(mockYtdlpExecutor.getSubtitles).toHaveBeenCalledWith('yt-123', 'en', '/tmp/subtitle-test');
      expect(mockSubtitleParser.parse).toHaveBeenCalledWith(vttContent, 'video-1', 'en');
      expect(mockSubtitleRepository.createMany).toHaveBeenCalledWith([
        {
          videoId: 'video-1',
          startMs: 1000,
          endMs: 3000,
          text: 'Hello from YouTube',
          segmentIndex: 0,
          language: 'en',
          isAutoGenerated: false,
        },
        {
          videoId: 'video-1',
          startMs: 4000,
          endMs: 6000,
          text: 'Second line',
          segmentIndex: 1,
          language: 'en',
          isAutoGenerated: false,
        },
      ]);
      expect(result).toEqual(parsedTrack);
    });

    it('should throw when video does not exist', async () => {
      mockVideoService.findById.mockRejectedValue(
        new AppError('Video not found', ErrorCategory.NOT_FOUND, 404, 'VIDEO_NOT_FOUND')
      );

      await expect(
        subtitleService.extractForVideo('nonexistent', 'en')
      ).rejects.toThrow(AppError);

      expect(mockSubtitleRepository.findByVideoId).not.toHaveBeenCalled();
      expect(mockYtdlpExecutor.getSubtitles).not.toHaveBeenCalled();
    });

    it('should throw when yt-dlp fails', async () => {
      mockVideoService.findById.mockResolvedValue({ id: 'video-1', youtubeId: 'yt-123' });
      mockSubtitleRepository.findByVideoId.mockResolvedValue([]);
      mockYtdlpExecutor.getSubtitles.mockRejectedValue(new Error('yt-dlp failed'));

      await expect(
        subtitleService.extractForVideo('video-1', 'en')
      ).rejects.toThrow('yt-dlp failed');

      // Should clean up temp dir even on error
      expect(fs.rm).toHaveBeenCalledWith('/tmp/subtitle-test', { recursive: true, force: true });
    });

    it('should clean up temp directory after extraction', async () => {
      const vttContent = `WEBVTT

00:00:01.000 --> 00:00:03.000
Test
`;
      mockVideoService.findById.mockResolvedValue({ id: 'video-1', youtubeId: 'yt-123' });
      mockSubtitleRepository.findByVideoId.mockResolvedValue([]);
      mockYtdlpExecutor.getSubtitles.mockResolvedValue(vttContent);
      mockSubtitleParser.parse.mockReturnValue({
        videoId: 'video-1',
        language: 'en',
        isAutoGenerated: false,
        cues: [{ start: 1, end: 3, text: 'Test' }],
      });
      mockSubtitleRepository.createMany.mockResolvedValue([]);

      await subtitleService.extractForVideo('video-1', 'en');

      expect(fs.rm).toHaveBeenCalledWith('/tmp/subtitle-test', { recursive: true, force: true });
    });

    it('should use default language en when not provided', async () => {
      mockVideoService.findById.mockResolvedValue({ id: 'video-1', youtubeId: 'yt-123' });
      mockSubtitleRepository.findByVideoId.mockResolvedValue([]);

      await subtitleService.extractForVideo('video-1');

      expect(mockSubtitleRepository.findByVideoId).toHaveBeenCalledWith('video-1', 'en');
    });
  });

  describe('findByVideoId', () => {
    it('should return SubtitleTrack when segments exist', async () => {
      const segments = [
        {
          videoId: 'video-1',
          startMs: 1000,
          endMs: 3000,
          text: 'Hello',
          segmentIndex: 0,
          language: 'en',
          isAutoGenerated: false,
        },
        {
          videoId: 'video-1',
          startMs: 4000,
          endMs: 6000,
          text: 'World',
          segmentIndex: 1,
          language: 'en',
          isAutoGenerated: false,
        },
      ];
      mockSubtitleRepository.findByVideoId.mockResolvedValue(segments);

      const result = await subtitleService.findByVideoId('video-1');

      expect(result).not.toBeNull();
      expect(result!.videoId).toBe('video-1');
      expect(result!.language).toBe('en');
      expect(result!.isAutoGenerated).toBe(false);
      expect(result!.cues).toHaveLength(2);
      expect(result!.cues[0]).toEqual({ start: 1, end: 3, text: 'Hello' });
      expect(result!.cues[1]).toEqual({ start: 4, end: 6, text: 'World' });
    });

    it('should return null when no segments', async () => {
      mockSubtitleRepository.findByVideoId.mockResolvedValue([]);

      const result = await subtitleService.findByVideoId('video-1');

      expect(result).toBeNull();
    });

    it('should filter by language when provided', async () => {
      const segments = [
        {
          videoId: 'video-1',
          startMs: 1000,
          endMs: 3000,
          text: 'Hola',
          segmentIndex: 0,
          language: 'es',
          isAutoGenerated: false,
        },
      ];
      mockSubtitleRepository.findByVideoId.mockResolvedValue(segments);

      const result = await subtitleService.findByVideoId('video-1', 'es');

      expect(mockSubtitleRepository.findByVideoId).toHaveBeenCalledWith('video-1', 'es');
      expect(result).not.toBeNull();
      expect(result!.language).toBe('es');
    });

    it('should handle auto-generated subtitles', async () => {
      const segments = [
        {
          videoId: 'video-1',
          startMs: 1000,
          endMs: 3000,
          text: 'Auto-generated text',
          segmentIndex: 0,
          language: 'en',
          isAutoGenerated: true,
        },
      ];
      mockSubtitleRepository.findByVideoId.mockResolvedValue(segments);

      const result = await subtitleService.findByVideoId('video-1');

      expect(result).not.toBeNull();
      expect(result!.isAutoGenerated).toBe(true);
    });
  });
});
