import { describe, it, expect } from 'vitest';
import { VttParser } from '../parsers/vtt-parser';

describe('VttParser', () => {
  const parser = new VttParser();

  describe('parse', () => {
    it('should parse valid VTT content with multiple cues', () => {
      const vtt = `WEBVTT

00:00:01.000 --> 00:00:03.000
Hello world

00:00:04.000 --> 00:00:06.000
Second cue
`;
      const result = parser.parse(vtt, 'video-123', 'en');

      expect(result.videoId).toBe('video-123');
      expect(result.language).toBe('en');
      expect(result.isAutoGenerated).toBe(false);
      expect(result.cues).toHaveLength(2);
      expect(result.cues[0]).toEqual({ start: 1, end: 3, text: 'Hello world' });
      expect(result.cues[1]).toEqual({ start: 4, end: 6, text: 'Second cue' });
    });

    it('should handle WEBVTT header correctly', () => {
      const vtt = `WEBVTT
Kind: captions
Language: en

00:00:01.000 --> 00:00:03.000
Test cue
`;
      const result = parser.parse(vtt, 'video-123', 'en');

      expect(result.cues).toHaveLength(1);
      expect(result.cues[0].text).toBe('Test cue');
    });

    it('should parse timestamps in HH:MM:SS.mmm format', () => {
      const vtt = `WEBVTT

01:30:45.123 --> 02:15:30.456
Long format timestamp
`;
      const result = parser.parse(vtt, 'video-123', 'en');

      expect(result.cues[0].start).toBeCloseTo(5445.123, 2);
      expect(result.cues[0].end).toBeCloseTo(8130.456, 2);
    });

    it('should parse timestamps in MM:SS.mmm format', () => {
      const vtt = `WEBVTT

05:30.500 --> 10:45.250
Short format timestamp
`;
      const result = parser.parse(vtt, 'video-123', 'en');

      expect(result.cues[0].start).toBeCloseTo(330.5, 2);
      expect(result.cues[0].end).toBeCloseTo(645.25, 2);
    });

    it('should strip HTML tags from subtitle text', () => {
      const vtt = `WEBVTT

00:00:01.000 --> 00:00:03.000
<b>Bold text</b> and <i>italic text</i>
`;
      const result = parser.parse(vtt, 'video-123', 'en');

      expect(result.cues[0].text).toBe('Bold text and italic text');
    });

    it('should strip VTT formatting tags', () => {
      const vtt = `WEBVTT

00:00:01.000 --> 00:00:03.000
<c.green>Green text</c> and <c>Default</c>
`;
      const result = parser.parse(vtt, 'video-123', 'en');

      expect(result.cues[0].text).toBe('Green text and Default');
    });

    it('should decode HTML entities', () => {
      const vtt = `WEBVTT

00:00:01.000 --> 00:00:03.000
Tom &amp; Jerry &lt;forever&gt; &quot;friends&quot;
`;
      const result = parser.parse(vtt, 'video-123', 'en');

      expect(result.cues[0].text).toBe('Tom & Jerry <forever> "friends"');
    });

    it('should handle empty VTT (no cues)', () => {
      const vtt = `WEBVTT

`;
      const result = parser.parse(vtt, 'video-123', 'en');

      expect(result.cues).toHaveLength(0);
      expect(result.videoId).toBe('video-123');
      expect(result.language).toBe('en');
    });

    it('should handle malformed VTT gracefully', () => {
      const vtt = `This is not valid VTT content
Just some random text
No timestamps here
`;
      const result = parser.parse(vtt, 'video-123', 'en');

      expect(result.cues).toHaveLength(0);
    });

    it('should sort cues by start time', () => {
      const vtt = `WEBVTT

00:00:10.000 --> 00:00:12.000
Third cue

00:00:01.000 --> 00:00:03.000
First cue

00:00:05.000 --> 00:00:07.000
Second cue
`;
      const result = parser.parse(vtt, 'video-123', 'en');

      expect(result.cues[0].text).toBe('First cue');
      expect(result.cues[1].text).toBe('Second cue');
      expect(result.cues[2].text).toBe('Third cue');
    });

    it('should preserve videoId and language in output', () => {
      const vtt = `WEBVTT

00:00:01.000 --> 00:00:03.000
Test
`;
      const result = parser.parse(vtt, 'my-video-id', 'es');

      expect(result.videoId).toBe('my-video-id');
      expect(result.language).toBe('es');
    });

    it('should handle multi-line cue text', () => {
      const vtt = `WEBVTT

00:00:01.000 --> 00:00:03.000
Line one
Line two
Line three
`;
      const result = parser.parse(vtt, 'video-123', 'en');

      expect(result.cues[0].text).toBe('Line one Line two Line three');
    });

    it('should skip cues with empty text after stripping', () => {
      const vtt = `WEBVTT

00:00:01.000 --> 00:00:03.000
<b></b>

00:00:04.000 --> 00:00:06.000
Real text
`;
      const result = parser.parse(vtt, 'video-123', 'en');

      expect(result.cues).toHaveLength(1);
      expect(result.cues[0].text).toBe('Real text');
    });

    it('should handle CRLF line endings', () => {
      const vtt = 'WEBVTT\r\n\r\n00:00:01.000 --> 00:00:03.000\r\nCRLF test';
      const result = parser.parse(vtt, 'video-123', 'en');

      expect(result.cues).toHaveLength(1);
      expect(result.cues[0].text).toBe('CRLF test');
    });

    it('should handle cue with no number identifier', () => {
      const vtt = `WEBVTT

00:00:01.000 --> 00:00:03.000
No cue number
`;
      const result = parser.parse(vtt, 'video-123', 'en');

      expect(result.cues).toHaveLength(1);
      expect(result.cues[0].text).toBe('No cue number');
    });
  });
});
