import { describe, it, expect } from 'vitest';
import { CreateVideoRequestSchema } from '../video.schema';
import { SubtitleCueSchema, SubtitleTrackSchema } from '../subtitle.schema';

describe('Zod Schemas', () => {
  describe('CreateVideoRequestSchema', () => {
    it('should accept valid YouTube URLs', () => {
      const validUrls = [
        'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        'https://youtube.com/watch?v=dQw4w9WgXcQ',
        'https://youtu.be/dQw4w9WgXcQ',
        'http://www.youtube.com/watch?v=dQw4w9WgXcQ',
      ];

      for (const url of validUrls) {
        const result = CreateVideoRequestSchema.safeParse({ url });
        expect(result.success).toBe(true);
      }
    });

    it('should reject non-YouTube URLs', () => {
      const invalidUrls = [
        'https://vimeo.com/123456',
        'https://example.com',
        'https://youtube.com/shorts/abc123',
        'https://youtube.com/channel/abc',
        'not-a-url',
      ];

      for (const url of invalidUrls) {
        const result = CreateVideoRequestSchema.safeParse({ url });
        expect(result.success).toBe(false);
      }
    });

    it('should reject empty strings', () => {
      const result = CreateVideoRequestSchema.safeParse({ url: '' });
      expect(result.success).toBe(false);
    });

    it('should default language to en', () => {
      const result = CreateVideoRequestSchema.safeParse({
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      });
      expect(result.success).toBe(true);
      if (result.success) {
        expect(result.data.language).toBe('en');
      }
    });

    it('should accept custom language', () => {
      const result = CreateVideoRequestSchema.safeParse({
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        language: 'es',
      });
      expect(result.success).toBe(true);
      if (result.success) {
        expect(result.data.language).toBe('es');
      }
    });

    it('should reject missing url field', () => {
      const result = CreateVideoRequestSchema.safeParse({});
      expect(result.success).toBe(false);
    });
  });

  describe('SubtitleCueSchema', () => {
    it('should validate correct cue structure', () => {
      const result = SubtitleCueSchema.safeParse({
        start: 0,
        end: 5,
        text: 'Hello world',
      });
      expect(result.success).toBe(true);
    });

    it('should reject negative start time', () => {
      const result = SubtitleCueSchema.safeParse({
        start: -1,
        end: 5,
        text: 'Hello',
      });
      expect(result.success).toBe(false);
    });

    it('should reject negative end time', () => {
      const result = SubtitleCueSchema.safeParse({
        start: 0,
        end: -1,
        text: 'Hello',
      });
      expect(result.success).toBe(false);
    });

    it('should reject empty text', () => {
      const result = SubtitleCueSchema.safeParse({
        start: 0,
        end: 5,
        text: '',
      });
      expect(result.success).toBe(false);
    });

    it('should reject missing fields', () => {
      const result = SubtitleCueSchema.safeParse({
        start: 0,
        // missing end and text
      });
      expect(result.success).toBe(false);
    });

    it('should accept zero start time', () => {
      const result = SubtitleCueSchema.safeParse({
        start: 0,
        end: 5,
        text: 'Start of video',
      });
      expect(result.success).toBe(true);
    });

    it('should accept decimal times', () => {
      const result = SubtitleCueSchema.safeParse({
        start: 1.5,
        end: 3.7,
        text: 'Decimal timestamps',
      });
      expect(result.success).toBe(true);
    });
  });

  describe('SubtitleTrackSchema', () => {
    it('should validate correct track structure', () => {
      const result = SubtitleTrackSchema.safeParse({
        videoId: 'video-123',
        language: 'en',
        isAutoGenerated: false,
        cues: [
          { start: 0, end: 5, text: 'Hello' },
          { start: 5, end: 10, text: 'World' },
        ],
      });
      expect(result.success).toBe(true);
    });

    it('should accept empty cues array', () => {
      const result = SubtitleTrackSchema.safeParse({
        videoId: 'video-123',
        language: 'en',
        isAutoGenerated: false,
        cues: [],
      });
      expect(result.success).toBe(true);
    });

    it('should reject missing videoId', () => {
      const result = SubtitleTrackSchema.safeParse({
        language: 'en',
        isAutoGenerated: false,
        cues: [],
      });
      expect(result.success).toBe(false);
    });

    it('should reject missing language', () => {
      const result = SubtitleTrackSchema.safeParse({
        videoId: 'video-123',
        isAutoGenerated: false,
        cues: [],
      });
      expect(result.success).toBe(false);
    });

    it('should reject missing isAutoGenerated', () => {
      const result = SubtitleTrackSchema.safeParse({
        videoId: 'video-123',
        language: 'en',
        cues: [],
      });
      expect(result.success).toBe(false);
    });

    it('should reject invalid cue in array', () => {
      const result = SubtitleTrackSchema.safeParse({
        videoId: 'video-123',
        language: 'en',
        isAutoGenerated: false,
        cues: [
          { start: 0, end: 5, text: 'Valid' },
          { start: -1, end: 5, text: 'Invalid' },
        ],
      });
      expect(result.success).toBe(false);
    });

    it('should accept auto-generated tracks', () => {
      const result = SubtitleTrackSchema.safeParse({
        videoId: 'video-123',
        language: 'en',
        isAutoGenerated: true,
        cues: [{ start: 0, end: 5, text: 'Auto-generated' }],
      });
      expect(result.success).toBe(true);
    });
  });
});
